/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackDotjsRouteImport } from './routes/track[.]js'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SetupAdminRouteImport } from './routes/setup-admin'
import { Route as PrivacybeleidRouteImport } from './routes/privacybeleid'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AlgemeneVoorwaardenRouteImport } from './routes/algemene-voorwaarden'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedServerRouteImport } from './routes/_authenticated/server'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ApiPublicSitePingRouteImport } from './routes/api/public/site-ping'
import { Route as ApiPublicSiteErrorRouteImport } from './routes/api/public/site-error'
import { Route as ApiPublicHooksExpireAccountsRouteImport } from './routes/api/public/hooks/expire-accounts'
import { Route as AuthenticatedPortalProjectenProjectIdRouteImport } from './routes/_authenticated/portal.projecten.$projectId'
import { Route as AuthenticatedAdminProjectenProjectIdRouteImport } from './routes/_authenticated/admin.projecten.$projectId'

const TrackDotjsRoute = TrackDotjsRouteImport.update({
  id: '/track.js',
  path: '/track.js',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupAdminRoute = SetupAdminRouteImport.update({
  id: '/setup-admin',
  path: '/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacybeleidRoute = PrivacybeleidRouteImport.update({
  id: '/privacybeleid',
  path: '/privacybeleid',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgemeneVoorwaardenRoute = AlgemeneVoorwaardenRouteImport.update({
  id: '/algemene-voorwaarden',
  path: '/algemene-voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedServerRoute = AuthenticatedServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicSitePingRoute = ApiPublicSitePingRouteImport.update({
  id: '/api/public/site-ping',
  path: '/api/public/site-ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSiteErrorRoute = ApiPublicSiteErrorRouteImport.update({
  id: '/api/public/site-error',
  path: '/api/public/site-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksExpireAccountsRoute =
  ApiPublicHooksExpireAccountsRouteImport.update({
    id: '/api/public/hooks/expire-accounts',
    path: '/api/public/hooks/expire-accounts',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPortalProjectenProjectIdRoute =
  AuthenticatedPortalProjectenProjectIdRouteImport.update({
    id: '/projecten/$projectId',
    path: '/projecten/$projectId',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedAdminProjectenProjectIdRoute =
  AuthenticatedAdminProjectenProjectIdRouteImport.update({
    id: '/projecten/$projectId',
    path: '/projecten/$projectId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/login': typeof LoginRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/setup-admin': typeof SetupAdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track.js': typeof TrackDotjsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/server': typeof AuthenticatedServerRoute
  '/api/public/site-error': typeof ApiPublicSiteErrorRoute
  '/api/public/site-ping': typeof ApiPublicSitePingRoute
  '/admin/projecten/$projectId': typeof AuthenticatedAdminProjectenProjectIdRoute
  '/portal/projecten/$projectId': typeof AuthenticatedPortalProjectenProjectIdRoute
  '/api/public/hooks/expire-accounts': typeof ApiPublicHooksExpireAccountsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/login': typeof LoginRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/setup-admin': typeof SetupAdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track.js': typeof TrackDotjsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/server': typeof AuthenticatedServerRoute
  '/api/public/site-error': typeof ApiPublicSiteErrorRoute
  '/api/public/site-ping': typeof ApiPublicSitePingRoute
  '/admin/projecten/$projectId': typeof AuthenticatedAdminProjectenProjectIdRoute
  '/portal/projecten/$projectId': typeof AuthenticatedPortalProjectenProjectIdRoute
  '/api/public/hooks/expire-accounts': typeof ApiPublicHooksExpireAccountsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/login': typeof LoginRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/setup-admin': typeof SetupAdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track.js': typeof TrackDotjsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/server': typeof AuthenticatedServerRoute
  '/api/public/site-error': typeof ApiPublicSiteErrorRoute
  '/api/public/site-ping': typeof ApiPublicSitePingRoute
  '/_authenticated/admin/projecten/$projectId': typeof AuthenticatedAdminProjectenProjectIdRoute
  '/_authenticated/portal/projecten/$projectId': typeof AuthenticatedPortalProjectenProjectIdRoute
  '/api/public/hooks/expire-accounts': typeof ApiPublicHooksExpireAccountsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/algemene-voorwaarden'
    | '/login'
    | '/privacybeleid'
    | '/setup-admin'
    | '/sitemap.xml'
    | '/track.js'
    | '/account'
    | '/admin'
    | '/portal'
    | '/server'
    | '/api/public/site-error'
    | '/api/public/site-ping'
    | '/admin/projecten/$projectId'
    | '/portal/projecten/$projectId'
    | '/api/public/hooks/expire-accounts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/algemene-voorwaarden'
    | '/login'
    | '/privacybeleid'
    | '/setup-admin'
    | '/sitemap.xml'
    | '/track.js'
    | '/account'
    | '/admin'
    | '/portal'
    | '/server'
    | '/api/public/site-error'
    | '/api/public/site-ping'
    | '/admin/projecten/$projectId'
    | '/portal/projecten/$projectId'
    | '/api/public/hooks/expire-accounts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/algemene-voorwaarden'
    | '/login'
    | '/privacybeleid'
    | '/setup-admin'
    | '/sitemap.xml'
    | '/track.js'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/_authenticated/server'
    | '/api/public/site-error'
    | '/api/public/site-ping'
    | '/_authenticated/admin/projecten/$projectId'
    | '/_authenticated/portal/projecten/$projectId'
    | '/api/public/hooks/expire-accounts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AlgemeneVoorwaardenRoute: typeof AlgemeneVoorwaardenRoute
  LoginRoute: typeof LoginRoute
  PrivacybeleidRoute: typeof PrivacybeleidRoute
  SetupAdminRoute: typeof SetupAdminRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackDotjsRoute: typeof TrackDotjsRoute
  ApiPublicSiteErrorRoute: typeof ApiPublicSiteErrorRoute
  ApiPublicSitePingRoute: typeof ApiPublicSitePingRoute
  ApiPublicHooksExpireAccountsRoute: typeof ApiPublicHooksExpireAccountsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track.js': {
      id: '/track.js'
      path: '/track.js'
      fullPath: '/track.js'
      preLoaderRoute: typeof TrackDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-admin': {
      id: '/setup-admin'
      path: '/setup-admin'
      fullPath: '/setup-admin'
      preLoaderRoute: typeof SetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacybeleid': {
      id: '/privacybeleid'
      path: '/privacybeleid'
      fullPath: '/privacybeleid'
      preLoaderRoute: typeof PrivacybeleidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algemene-voorwaarden': {
      id: '/algemene-voorwaarden'
      path: '/algemene-voorwaarden'
      fullPath: '/algemene-voorwaarden'
      preLoaderRoute: typeof AlgemeneVoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/server': {
      id: '/_authenticated/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof AuthenticatedServerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/site-ping': {
      id: '/api/public/site-ping'
      path: '/api/public/site-ping'
      fullPath: '/api/public/site-ping'
      preLoaderRoute: typeof ApiPublicSitePingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site-error': {
      id: '/api/public/site-error'
      path: '/api/public/site-error'
      fullPath: '/api/public/site-error'
      preLoaderRoute: typeof ApiPublicSiteErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/expire-accounts': {
      id: '/api/public/hooks/expire-accounts'
      path: '/api/public/hooks/expire-accounts'
      fullPath: '/api/public/hooks/expire-accounts'
      preLoaderRoute: typeof ApiPublicHooksExpireAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/projecten/$projectId': {
      id: '/_authenticated/portal/projecten/$projectId'
      path: '/projecten/$projectId'
      fullPath: '/portal/projecten/$projectId'
      preLoaderRoute: typeof AuthenticatedPortalProjectenProjectIdRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/admin/projecten/$projectId': {
      id: '/_authenticated/admin/projecten/$projectId'
      path: '/projecten/$projectId'
      fullPath: '/admin/projecten/$projectId'
      preLoaderRoute: typeof AuthenticatedAdminProjectenProjectIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminProjectenProjectIdRoute: typeof AuthenticatedAdminProjectenProjectIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminProjectenProjectIdRoute:
    AuthenticatedAdminProjectenProjectIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalProjectenProjectIdRoute: typeof AuthenticatedPortalProjectenProjectIdRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalProjectenProjectIdRoute:
    AuthenticatedPortalProjectenProjectIdRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
  AuthenticatedServerRoute: typeof AuthenticatedServerRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
  AuthenticatedServerRoute: AuthenticatedServerRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AlgemeneVoorwaardenRoute: AlgemeneVoorwaardenRoute,
  LoginRoute: LoginRoute,
  PrivacybeleidRoute: PrivacybeleidRoute,
  SetupAdminRoute: SetupAdminRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackDotjsRoute: TrackDotjsRoute,
  ApiPublicSiteErrorRoute: ApiPublicSiteErrorRoute,
  ApiPublicSitePingRoute: ApiPublicSitePingRoute,
  ApiPublicHooksExpireAccountsRoute: ApiPublicHooksExpireAccountsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
