/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackDotjsRouteImport } from './routes/track[.]js'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SetupAdminRouteImport } from './routes/setup-admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ApiPublicSitePingRouteImport } from './routes/api/public/site-ping'
import { Route as ApiPublicSiteErrorRouteImport } from './routes/api/public/site-error'
import { Route as ApiPublicHooksExpireAccountsRouteImport } from './routes/api/public/hooks/expire-accounts'

const TrackDotjsRoute = TrackDotjsRouteImport.update({
  id: '/track.js',
  path: '/track.js',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupAdminRoute = SetupAdminRouteImport.update({
  id: '/setup-admin',
  path: '/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicSitePingRoute = ApiPublicSitePingRouteImport.update({
  id: '/api/public/site-ping',
  path: '/api/public/site-ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSiteErrorRoute = ApiPublicSiteErrorRouteImport.update({
  id: '/api/public/site-error',
  path: '/api/public/site-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksExpireAccountsRoute =
  ApiPublicHooksExpireAccountsRouteImport.update({
    id: '/api/public/hooks/expire-accounts',
    path: '/api/public/hooks/expire-accounts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup-admin': typeof SetupAdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track.js': typeof TrackDotjsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/api/public/site-error': typeof ApiPublicSiteErrorRoute
  '/api/public/site-ping': typeof ApiPublicSitePingRoute
  '/api/public/hooks/expire-accounts': typeof ApiPublicHooksExpireAccountsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup-admin': typeof SetupAdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track.js': typeof TrackDotjsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/api/public/site-error': typeof ApiPublicSiteErrorRoute
  '/api/public/site-ping': typeof ApiPublicSitePingRoute
  '/api/public/hooks/expire-accounts': typeof ApiPublicHooksExpireAccountsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/setup-admin': typeof SetupAdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track.js': typeof TrackDotjsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/api/public/site-error': typeof ApiPublicSiteErrorRoute
  '/api/public/site-ping': typeof ApiPublicSitePingRoute
  '/api/public/hooks/expire-accounts': typeof ApiPublicHooksExpireAccountsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup-admin'
    | '/sitemap.xml'
    | '/track.js'
    | '/account'
    | '/admin'
    | '/portal'
    | '/api/public/site-error'
    | '/api/public/site-ping'
    | '/api/public/hooks/expire-accounts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup-admin'
    | '/sitemap.xml'
    | '/track.js'
    | '/account'
    | '/admin'
    | '/portal'
    | '/api/public/site-error'
    | '/api/public/site-ping'
    | '/api/public/hooks/expire-accounts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/setup-admin'
    | '/sitemap.xml'
    | '/track.js'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/api/public/site-error'
    | '/api/public/site-ping'
    | '/api/public/hooks/expire-accounts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupAdminRoute: typeof SetupAdminRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackDotjsRoute: typeof TrackDotjsRoute
  ApiPublicSiteErrorRoute: typeof ApiPublicSiteErrorRoute
  ApiPublicSitePingRoute: typeof ApiPublicSitePingRoute
  ApiPublicHooksExpireAccountsRoute: typeof ApiPublicHooksExpireAccountsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track.js': {
      id: '/track.js'
      path: '/track.js'
      fullPath: '/track.js'
      preLoaderRoute: typeof TrackDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-admin': {
      id: '/setup-admin'
      path: '/setup-admin'
      fullPath: '/setup-admin'
      preLoaderRoute: typeof SetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/site-ping': {
      id: '/api/public/site-ping'
      path: '/api/public/site-ping'
      fullPath: '/api/public/site-ping'
      preLoaderRoute: typeof ApiPublicSitePingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site-error': {
      id: '/api/public/site-error'
      path: '/api/public/site-error'
      fullPath: '/api/public/site-error'
      preLoaderRoute: typeof ApiPublicSiteErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/expire-accounts': {
      id: '/api/public/hooks/expire-accounts'
      path: '/api/public/hooks/expire-accounts'
      fullPath: '/api/public/hooks/expire-accounts'
      preLoaderRoute: typeof ApiPublicHooksExpireAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupAdminRoute: SetupAdminRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackDotjsRoute: TrackDotjsRoute,
  ApiPublicSiteErrorRoute: ApiPublicSiteErrorRoute,
  ApiPublicSitePingRoute: ApiPublicSitePingRoute,
  ApiPublicHooksExpireAccountsRoute: ApiPublicHooksExpireAccountsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
