/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordpressOfMaatwerkRouteImport } from './routes/wordpress-of-maatwerk'
import { Route as WerkwijzeRouteImport } from './routes/werkwijze'
import { Route as WebsiteLatenVernieuwenRouteImport } from './routes/website-laten-vernieuwen'
import { Route as WebsiteLatenMakenWinschotenRouteImport } from './routes/website-laten-maken-winschoten'
import { Route as WebsiteLatenMakenVeendamRouteImport } from './routes/website-laten-maken-veendam'
import { Route as WebsiteLatenMakenStadskanaalRouteImport } from './routes/website-laten-maken-stadskanaal'
import { Route as WebsiteLatenMakenSneekRouteImport } from './routes/website-laten-maken-sneek'
import { Route as WebsiteLatenMakenSchoonheidssalonRouteImport } from './routes/website-laten-maken-schoonheidssalon'
import { Route as WebsiteLatenMakenSchilderRouteImport } from './routes/website-laten-maken-schilder'
import { Route as WebsiteLatenMakenRodenRouteImport } from './routes/website-laten-maken-roden'
import { Route as WebsiteLatenMakenRestaurantRouteImport } from './routes/website-laten-maken-restaurant'
import { Route as WebsiteLatenMakenPedicureRouteImport } from './routes/website-laten-maken-pedicure'
import { Route as WebsiteLatenMakenNagelstudioRouteImport } from './routes/website-laten-maken-nagelstudio'
import { Route as WebsiteLatenMakenMeppelRouteImport } from './routes/website-laten-maken-meppel'
import { Route as WebsiteLatenMakenMakelaarRouteImport } from './routes/website-laten-maken-makelaar'
import { Route as WebsiteLatenMakenLoodgieterRouteImport } from './routes/website-laten-maken-loodgieter'
import { Route as WebsiteLatenMakenLeeuwardenRouteImport } from './routes/website-laten-maken-leeuwarden'
import { Route as WebsiteLatenMakenKlusbedrijfRouteImport } from './routes/website-laten-maken-klusbedrijf'
import { Route as WebsiteLatenMakenKapsalonRouteImport } from './routes/website-laten-maken-kapsalon'
import { Route as WebsiteLatenMakenHovenierRouteImport } from './routes/website-laten-maken-hovenier'
import { Route as WebsiteLatenMakenHoogezandRouteImport } from './routes/website-laten-maken-hoogezand'
import { Route as WebsiteLatenMakenHoogeveenRouteImport } from './routes/website-laten-maken-hoogeveen'
import { Route as WebsiteLatenMakenHeerenveenRouteImport } from './routes/website-laten-maken-heerenveen'
import { Route as WebsiteLatenMakenGroningenRouteImport } from './routes/website-laten-maken-groningen'
import { Route as WebsiteLatenMakenEmmenRouteImport } from './routes/website-laten-maken-emmen'
import { Route as WebsiteLatenMakenDrachtenRouteImport } from './routes/website-laten-maken-drachten'
import { Route as WebsiteLatenMakenCoevordenRouteImport } from './routes/website-laten-maken-coevorden'
import { Route as WebsiteLatenMakenCateringbedrijfRouteImport } from './routes/website-laten-maken-cateringbedrijf'
import { Route as WebsiteLatenMakenBoekhouderRouteImport } from './routes/website-laten-maken-boekhouder'
import { Route as WebsiteLatenMakenBloemistRouteImport } from './routes/website-laten-maken-bloemist'
import { Route as WebsiteLatenMakenAutorijschoolRouteImport } from './routes/website-laten-maken-autorijschool'
import { Route as WebsiteLatenMakenAutobedrijfRouteImport } from './routes/website-laten-maken-autobedrijf'
import { Route as WebsiteLatenMakenAssenRouteImport } from './routes/website-laten-maken-assen'
import { Route as WebsiteLatenMakenRouteImport } from './routes/website-laten-maken'
import { Route as WebshopLatenMakenRouteImport } from './routes/webshop-laten-maken'
import { Route as WebdesignRouteImport } from './routes/webdesign'
import { Route as TrackDotjsRouteImport } from './routes/track[.]js'
import { Route as TarievenRouteImport } from './routes/tarieven'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as PrivacybeleidRouteImport } from './routes/privacybeleid'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as OnderhoudHostingRouteImport } from './routes/onderhoud-hosting'
import { Route as MeerDienstenRouteImport } from './routes/meer-diensten'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as AlgemeneVoorwaardenRouteImport } from './routes/algemene-voorwaarden'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedServerRouteImport } from './routes/_authenticated/server'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api/telegram/webhook'
import { Route as ApiPublicSitePingRouteImport } from './routes/api/public/site-ping'
import { Route as ApiPublicSiteErrorRouteImport } from './routes/api/public/site-error'
import { Route as AuthenticatedAdminRollenRouteImport } from './routes/_authenticated/admin.rollen'
import { Route as AuthenticatedAdminProjectenRouteImport } from './routes/_authenticated/admin.projecten'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminInstellingenRouteImport } from './routes/_authenticated/admin.instellingen'
import { Route as AuthenticatedAdminChangesRouteImport } from './routes/_authenticated/admin.changes'
import { Route as AuthenticatedAdminAccountsRouteImport } from './routes/_authenticated/admin.accounts'
import { Route as ApiPublicHooksExpireAccountsRouteImport } from './routes/api/public/hooks/expire-accounts'
import { Route as AuthenticatedPortalProjectenProjectIdRouteImport } from './routes/_authenticated/portal.projecten.$projectId'
import { Route as AuthenticatedAdminRollenRoleIdRouteImport } from './routes/_authenticated/admin.rollen.$roleId'
import { Route as AuthenticatedAdminProjectenProjectIdRouteImport } from './routes/_authenticated/admin.projecten.$projectId'
import { Route as AuthenticatedAdminChangesChangeIdRouteImport } from './routes/_authenticated/admin.changes.$changeId'
import { Route as AuthenticatedAdminAccountsAccountIdRouteImport } from './routes/_authenticated/admin.accounts.$accountId'

const WordpressOfMaatwerkRoute = WordpressOfMaatwerkRouteImport.update({
  id: '/wordpress-of-maatwerk',
  path: '/wordpress-of-maatwerk',
  getParentRoute: () => rootRouteImport,
} as any)
const WerkwijzeRoute = WerkwijzeRouteImport.update({
  id: '/werkwijze',
  path: '/werkwijze',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteLatenVernieuwenRoute = WebsiteLatenVernieuwenRouteImport.update({
  id: '/website-laten-vernieuwen',
  path: '/website-laten-vernieuwen',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteLatenMakenWinschotenRoute =
  WebsiteLatenMakenWinschotenRouteImport.update({
    id: '/website-laten-maken-winschoten',
    path: '/website-laten-maken-winschoten',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenVeendamRoute =
  WebsiteLatenMakenVeendamRouteImport.update({
    id: '/website-laten-maken-veendam',
    path: '/website-laten-maken-veendam',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenStadskanaalRoute =
  WebsiteLatenMakenStadskanaalRouteImport.update({
    id: '/website-laten-maken-stadskanaal',
    path: '/website-laten-maken-stadskanaal',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenSneekRoute = WebsiteLatenMakenSneekRouteImport.update({
  id: '/website-laten-maken-sneek',
  path: '/website-laten-maken-sneek',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteLatenMakenSchoonheidssalonRoute =
  WebsiteLatenMakenSchoonheidssalonRouteImport.update({
    id: '/website-laten-maken-schoonheidssalon',
    path: '/website-laten-maken-schoonheidssalon',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenSchilderRoute =
  WebsiteLatenMakenSchilderRouteImport.update({
    id: '/website-laten-maken-schilder',
    path: '/website-laten-maken-schilder',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenRodenRoute = WebsiteLatenMakenRodenRouteImport.update({
  id: '/website-laten-maken-roden',
  path: '/website-laten-maken-roden',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteLatenMakenRestaurantRoute =
  WebsiteLatenMakenRestaurantRouteImport.update({
    id: '/website-laten-maken-restaurant',
    path: '/website-laten-maken-restaurant',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenPedicureRoute =
  WebsiteLatenMakenPedicureRouteImport.update({
    id: '/website-laten-maken-pedicure',
    path: '/website-laten-maken-pedicure',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenNagelstudioRoute =
  WebsiteLatenMakenNagelstudioRouteImport.update({
    id: '/website-laten-maken-nagelstudio',
    path: '/website-laten-maken-nagelstudio',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenMeppelRoute = WebsiteLatenMakenMeppelRouteImport.update({
  id: '/website-laten-maken-meppel',
  path: '/website-laten-maken-meppel',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteLatenMakenMakelaarRoute =
  WebsiteLatenMakenMakelaarRouteImport.update({
    id: '/website-laten-maken-makelaar',
    path: '/website-laten-maken-makelaar',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenLoodgieterRoute =
  WebsiteLatenMakenLoodgieterRouteImport.update({
    id: '/website-laten-maken-loodgieter',
    path: '/website-laten-maken-loodgieter',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenLeeuwardenRoute =
  WebsiteLatenMakenLeeuwardenRouteImport.update({
    id: '/website-laten-maken-leeuwarden',
    path: '/website-laten-maken-leeuwarden',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenKlusbedrijfRoute =
  WebsiteLatenMakenKlusbedrijfRouteImport.update({
    id: '/website-laten-maken-klusbedrijf',
    path: '/website-laten-maken-klusbedrijf',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenKapsalonRoute =
  WebsiteLatenMakenKapsalonRouteImport.update({
    id: '/website-laten-maken-kapsalon',
    path: '/website-laten-maken-kapsalon',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenHovenierRoute =
  WebsiteLatenMakenHovenierRouteImport.update({
    id: '/website-laten-maken-hovenier',
    path: '/website-laten-maken-hovenier',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenHoogezandRoute =
  WebsiteLatenMakenHoogezandRouteImport.update({
    id: '/website-laten-maken-hoogezand',
    path: '/website-laten-maken-hoogezand',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenHoogeveenRoute =
  WebsiteLatenMakenHoogeveenRouteImport.update({
    id: '/website-laten-maken-hoogeveen',
    path: '/website-laten-maken-hoogeveen',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenHeerenveenRoute =
  WebsiteLatenMakenHeerenveenRouteImport.update({
    id: '/website-laten-maken-heerenveen',
    path: '/website-laten-maken-heerenveen',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenGroningenRoute =
  WebsiteLatenMakenGroningenRouteImport.update({
    id: '/website-laten-maken-groningen',
    path: '/website-laten-maken-groningen',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenEmmenRoute = WebsiteLatenMakenEmmenRouteImport.update({
  id: '/website-laten-maken-emmen',
  path: '/website-laten-maken-emmen',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteLatenMakenDrachtenRoute =
  WebsiteLatenMakenDrachtenRouteImport.update({
    id: '/website-laten-maken-drachten',
    path: '/website-laten-maken-drachten',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenCoevordenRoute =
  WebsiteLatenMakenCoevordenRouteImport.update({
    id: '/website-laten-maken-coevorden',
    path: '/website-laten-maken-coevorden',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenCateringbedrijfRoute =
  WebsiteLatenMakenCateringbedrijfRouteImport.update({
    id: '/website-laten-maken-cateringbedrijf',
    path: '/website-laten-maken-cateringbedrijf',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenBoekhouderRoute =
  WebsiteLatenMakenBoekhouderRouteImport.update({
    id: '/website-laten-maken-boekhouder',
    path: '/website-laten-maken-boekhouder',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenBloemistRoute =
  WebsiteLatenMakenBloemistRouteImport.update({
    id: '/website-laten-maken-bloemist',
    path: '/website-laten-maken-bloemist',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenAutorijschoolRoute =
  WebsiteLatenMakenAutorijschoolRouteImport.update({
    id: '/website-laten-maken-autorijschool',
    path: '/website-laten-maken-autorijschool',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenAutobedrijfRoute =
  WebsiteLatenMakenAutobedrijfRouteImport.update({
    id: '/website-laten-maken-autobedrijf',
    path: '/website-laten-maken-autobedrijf',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsiteLatenMakenAssenRoute = WebsiteLatenMakenAssenRouteImport.update({
  id: '/website-laten-maken-assen',
  path: '/website-laten-maken-assen',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteLatenMakenRoute = WebsiteLatenMakenRouteImport.update({
  id: '/website-laten-maken',
  path: '/website-laten-maken',
  getParentRoute: () => rootRouteImport,
} as any)
const WebshopLatenMakenRoute = WebshopLatenMakenRouteImport.update({
  id: '/webshop-laten-maken',
  path: '/webshop-laten-maken',
  getParentRoute: () => rootRouteImport,
} as any)
const WebdesignRoute = WebdesignRouteImport.update({
  id: '/webdesign',
  path: '/webdesign',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackDotjsRoute = TrackDotjsRouteImport.update({
  id: '/track.js',
  path: '/track.js',
  getParentRoute: () => rootRouteImport,
} as any)
const TarievenRoute = TarievenRouteImport.update({
  id: '/tarieven',
  path: '/tarieven',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacybeleidRoute = PrivacybeleidRouteImport.update({
  id: '/privacybeleid',
  path: '/privacybeleid',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const OnderhoudHostingRoute = OnderhoudHostingRouteImport.update({
  id: '/onderhoud-hosting',
  path: '/onderhoud-hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const MeerDienstenRoute = MeerDienstenRouteImport.update({
  id: '/meer-diensten',
  path: '/meer-diensten',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgemeneVoorwaardenRoute = AlgemeneVoorwaardenRouteImport.update({
  id: '/algemene-voorwaarden',
  path: '/algemene-voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedServerRoute = AuthenticatedServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram/webhook',
  path: '/api/telegram/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSitePingRoute = ApiPublicSitePingRouteImport.update({
  id: '/api/public/site-ping',
  path: '/api/public/site-ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSiteErrorRoute = ApiPublicSiteErrorRouteImport.update({
  id: '/api/public/site-error',
  path: '/api/public/site-error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRollenRoute =
  AuthenticatedAdminRollenRouteImport.update({
    id: '/rollen',
    path: '/rollen',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectenRoute =
  AuthenticatedAdminProjectenRouteImport.update({
    id: '/projecten',
    path: '/projecten',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminInstellingenRoute =
  AuthenticatedAdminInstellingenRouteImport.update({
    id: '/instellingen',
    path: '/instellingen',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminChangesRoute =
  AuthenticatedAdminChangesRouteImport.update({
    id: '/changes',
    path: '/changes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAccountsRoute =
  AuthenticatedAdminAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicHooksExpireAccountsRoute =
  ApiPublicHooksExpireAccountsRouteImport.update({
    id: '/api/public/hooks/expire-accounts',
    path: '/api/public/hooks/expire-accounts',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPortalProjectenProjectIdRoute =
  AuthenticatedPortalProjectenProjectIdRouteImport.update({
    id: '/projecten/$projectId',
    path: '/projecten/$projectId',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedAdminRollenRoleIdRoute =
  AuthenticatedAdminRollenRoleIdRouteImport.update({
    id: '/$roleId',
    path: '/$roleId',
    getParentRoute: () => AuthenticatedAdminRollenRoute,
  } as any)
const AuthenticatedAdminProjectenProjectIdRoute =
  AuthenticatedAdminProjectenProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedAdminProjectenRoute,
  } as any)
const AuthenticatedAdminChangesChangeIdRoute =
  AuthenticatedAdminChangesChangeIdRouteImport.update({
    id: '/$changeId',
    path: '/$changeId',
    getParentRoute: () => AuthenticatedAdminChangesRoute,
  } as any)
const AuthenticatedAdminAccountsAccountIdRoute =
  AuthenticatedAdminAccountsAccountIdRouteImport.update({
    id: '/$accountId',
    path: '/$accountId',
    getParentRoute: () => AuthenticatedAdminAccountsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/branches': typeof BranchesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/meer-diensten': typeof MeerDienstenRoute
  '/onderhoud-hosting': typeof OnderhoudHostingRoute
  '/over-ons': typeof OverOnsRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/seo': typeof SeoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarieven': typeof TarievenRoute
  '/track.js': typeof TrackDotjsRoute
  '/webdesign': typeof WebdesignRoute
  '/webshop-laten-maken': typeof WebshopLatenMakenRoute
  '/website-laten-maken': typeof WebsiteLatenMakenRoute
  '/website-laten-maken-assen': typeof WebsiteLatenMakenAssenRoute
  '/website-laten-maken-autobedrijf': typeof WebsiteLatenMakenAutobedrijfRoute
  '/website-laten-maken-autorijschool': typeof WebsiteLatenMakenAutorijschoolRoute
  '/website-laten-maken-bloemist': typeof WebsiteLatenMakenBloemistRoute
  '/website-laten-maken-boekhouder': typeof WebsiteLatenMakenBoekhouderRoute
  '/website-laten-maken-cateringbedrijf': typeof WebsiteLatenMakenCateringbedrijfRoute
  '/website-laten-maken-coevorden': typeof WebsiteLatenMakenCoevordenRoute
  '/website-laten-maken-drachten': typeof WebsiteLatenMakenDrachtenRoute
  '/website-laten-maken-emmen': typeof WebsiteLatenMakenEmmenRoute
  '/website-laten-maken-groningen': typeof WebsiteLatenMakenGroningenRoute
  '/website-laten-maken-heerenveen': typeof WebsiteLatenMakenHeerenveenRoute
  '/website-laten-maken-hoogeveen': typeof WebsiteLatenMakenHoogeveenRoute
  '/website-laten-maken-hoogezand': typeof WebsiteLatenMakenHoogezandRoute
  '/website-laten-maken-hovenier': typeof WebsiteLatenMakenHovenierRoute
  '/website-laten-maken-kapsalon': typeof WebsiteLatenMakenKapsalonRoute
  '/website-laten-maken-klusbedrijf': typeof WebsiteLatenMakenKlusbedrijfRoute
  '/website-laten-maken-leeuwarden': typeof WebsiteLatenMakenLeeuwardenRoute
  '/website-laten-maken-loodgieter': typeof WebsiteLatenMakenLoodgieterRoute
  '/website-laten-maken-makelaar': typeof WebsiteLatenMakenMakelaarRoute
  '/website-laten-maken-meppel': typeof WebsiteLatenMakenMeppelRoute
  '/website-laten-maken-nagelstudio': typeof WebsiteLatenMakenNagelstudioRoute
  '/website-laten-maken-pedicure': typeof WebsiteLatenMakenPedicureRoute
  '/website-laten-maken-restaurant': typeof WebsiteLatenMakenRestaurantRoute
  '/website-laten-maken-roden': typeof WebsiteLatenMakenRodenRoute
  '/website-laten-maken-schilder': typeof WebsiteLatenMakenSchilderRoute
  '/website-laten-maken-schoonheidssalon': typeof WebsiteLatenMakenSchoonheidssalonRoute
  '/website-laten-maken-sneek': typeof WebsiteLatenMakenSneekRoute
  '/website-laten-maken-stadskanaal': typeof WebsiteLatenMakenStadskanaalRoute
  '/website-laten-maken-veendam': typeof WebsiteLatenMakenVeendamRoute
  '/website-laten-maken-winschoten': typeof WebsiteLatenMakenWinschotenRoute
  '/website-laten-vernieuwen': typeof WebsiteLatenVernieuwenRoute
  '/werkwijze': typeof WerkwijzeRoute
  '/wordpress-of-maatwerk': typeof WordpressOfMaatwerkRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/server': typeof AuthenticatedServerRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRouteWithChildren
  '/admin/changes': typeof AuthenticatedAdminChangesRouteWithChildren
  '/admin/instellingen': typeof AuthenticatedAdminInstellingenRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/projecten': typeof AuthenticatedAdminProjectenRouteWithChildren
  '/admin/rollen': typeof AuthenticatedAdminRollenRouteWithChildren
  '/api/public/site-error': typeof ApiPublicSiteErrorRoute
  '/api/public/site-ping': typeof ApiPublicSitePingRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/admin/accounts/$accountId': typeof AuthenticatedAdminAccountsAccountIdRoute
  '/admin/changes/$changeId': typeof AuthenticatedAdminChangesChangeIdRoute
  '/admin/projecten/$projectId': typeof AuthenticatedAdminProjectenProjectIdRoute
  '/admin/rollen/$roleId': typeof AuthenticatedAdminRollenRoleIdRoute
  '/portal/projecten/$projectId': typeof AuthenticatedPortalProjectenProjectIdRoute
  '/api/public/hooks/expire-accounts': typeof ApiPublicHooksExpireAccountsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/branches': typeof BranchesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/meer-diensten': typeof MeerDienstenRoute
  '/onderhoud-hosting': typeof OnderhoudHostingRoute
  '/over-ons': typeof OverOnsRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/seo': typeof SeoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarieven': typeof TarievenRoute
  '/track.js': typeof TrackDotjsRoute
  '/webdesign': typeof WebdesignRoute
  '/webshop-laten-maken': typeof WebshopLatenMakenRoute
  '/website-laten-maken': typeof WebsiteLatenMakenRoute
  '/website-laten-maken-assen': typeof WebsiteLatenMakenAssenRoute
  '/website-laten-maken-autobedrijf': typeof WebsiteLatenMakenAutobedrijfRoute
  '/website-laten-maken-autorijschool': typeof WebsiteLatenMakenAutorijschoolRoute
  '/website-laten-maken-bloemist': typeof WebsiteLatenMakenBloemistRoute
  '/website-laten-maken-boekhouder': typeof WebsiteLatenMakenBoekhouderRoute
  '/website-laten-maken-cateringbedrijf': typeof WebsiteLatenMakenCateringbedrijfRoute
  '/website-laten-maken-coevorden': typeof WebsiteLatenMakenCoevordenRoute
  '/website-laten-maken-drachten': typeof WebsiteLatenMakenDrachtenRoute
  '/website-laten-maken-emmen': typeof WebsiteLatenMakenEmmenRoute
  '/website-laten-maken-groningen': typeof WebsiteLatenMakenGroningenRoute
  '/website-laten-maken-heerenveen': typeof WebsiteLatenMakenHeerenveenRoute
  '/website-laten-maken-hoogeveen': typeof WebsiteLatenMakenHoogeveenRoute
  '/website-laten-maken-hoogezand': typeof WebsiteLatenMakenHoogezandRoute
  '/website-laten-maken-hovenier': typeof WebsiteLatenMakenHovenierRoute
  '/website-laten-maken-kapsalon': typeof WebsiteLatenMakenKapsalonRoute
  '/website-laten-maken-klusbedrijf': typeof WebsiteLatenMakenKlusbedrijfRoute
  '/website-laten-maken-leeuwarden': typeof WebsiteLatenMakenLeeuwardenRoute
  '/website-laten-maken-loodgieter': typeof WebsiteLatenMakenLoodgieterRoute
  '/website-laten-maken-makelaar': typeof WebsiteLatenMakenMakelaarRoute
  '/website-laten-maken-meppel': typeof WebsiteLatenMakenMeppelRoute
  '/website-laten-maken-nagelstudio': typeof WebsiteLatenMakenNagelstudioRoute
  '/website-laten-maken-pedicure': typeof WebsiteLatenMakenPedicureRoute
  '/website-laten-maken-restaurant': typeof WebsiteLatenMakenRestaurantRoute
  '/website-laten-maken-roden': typeof WebsiteLatenMakenRodenRoute
  '/website-laten-maken-schilder': typeof WebsiteLatenMakenSchilderRoute
  '/website-laten-maken-schoonheidssalon': typeof WebsiteLatenMakenSchoonheidssalonRoute
  '/website-laten-maken-sneek': typeof WebsiteLatenMakenSneekRoute
  '/website-laten-maken-stadskanaal': typeof WebsiteLatenMakenStadskanaalRoute
  '/website-laten-maken-veendam': typeof WebsiteLatenMakenVeendamRoute
  '/website-laten-maken-winschoten': typeof WebsiteLatenMakenWinschotenRoute
  '/website-laten-vernieuwen': typeof WebsiteLatenVernieuwenRoute
  '/werkwijze': typeof WerkwijzeRoute
  '/wordpress-of-maatwerk': typeof WordpressOfMaatwerkRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/server': typeof AuthenticatedServerRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRouteWithChildren
  '/admin/changes': typeof AuthenticatedAdminChangesRouteWithChildren
  '/admin/instellingen': typeof AuthenticatedAdminInstellingenRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/projecten': typeof AuthenticatedAdminProjectenRouteWithChildren
  '/admin/rollen': typeof AuthenticatedAdminRollenRouteWithChildren
  '/api/public/site-error': typeof ApiPublicSiteErrorRoute
  '/api/public/site-ping': typeof ApiPublicSitePingRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/admin/accounts/$accountId': typeof AuthenticatedAdminAccountsAccountIdRoute
  '/admin/changes/$changeId': typeof AuthenticatedAdminChangesChangeIdRoute
  '/admin/projecten/$projectId': typeof AuthenticatedAdminProjectenProjectIdRoute
  '/admin/rollen/$roleId': typeof AuthenticatedAdminRollenRoleIdRoute
  '/portal/projecten/$projectId': typeof AuthenticatedPortalProjectenProjectIdRoute
  '/api/public/hooks/expire-accounts': typeof ApiPublicHooksExpireAccountsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/branches': typeof BranchesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/meer-diensten': typeof MeerDienstenRoute
  '/onderhoud-hosting': typeof OnderhoudHostingRoute
  '/over-ons': typeof OverOnsRoute
  '/privacybeleid': typeof PrivacybeleidRoute
  '/seo': typeof SeoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarieven': typeof TarievenRoute
  '/track.js': typeof TrackDotjsRoute
  '/webdesign': typeof WebdesignRoute
  '/webshop-laten-maken': typeof WebshopLatenMakenRoute
  '/website-laten-maken': typeof WebsiteLatenMakenRoute
  '/website-laten-maken-assen': typeof WebsiteLatenMakenAssenRoute
  '/website-laten-maken-autobedrijf': typeof WebsiteLatenMakenAutobedrijfRoute
  '/website-laten-maken-autorijschool': typeof WebsiteLatenMakenAutorijschoolRoute
  '/website-laten-maken-bloemist': typeof WebsiteLatenMakenBloemistRoute
  '/website-laten-maken-boekhouder': typeof WebsiteLatenMakenBoekhouderRoute
  '/website-laten-maken-cateringbedrijf': typeof WebsiteLatenMakenCateringbedrijfRoute
  '/website-laten-maken-coevorden': typeof WebsiteLatenMakenCoevordenRoute
  '/website-laten-maken-drachten': typeof WebsiteLatenMakenDrachtenRoute
  '/website-laten-maken-emmen': typeof WebsiteLatenMakenEmmenRoute
  '/website-laten-maken-groningen': typeof WebsiteLatenMakenGroningenRoute
  '/website-laten-maken-heerenveen': typeof WebsiteLatenMakenHeerenveenRoute
  '/website-laten-maken-hoogeveen': typeof WebsiteLatenMakenHoogeveenRoute
  '/website-laten-maken-hoogezand': typeof WebsiteLatenMakenHoogezandRoute
  '/website-laten-maken-hovenier': typeof WebsiteLatenMakenHovenierRoute
  '/website-laten-maken-kapsalon': typeof WebsiteLatenMakenKapsalonRoute
  '/website-laten-maken-klusbedrijf': typeof WebsiteLatenMakenKlusbedrijfRoute
  '/website-laten-maken-leeuwarden': typeof WebsiteLatenMakenLeeuwardenRoute
  '/website-laten-maken-loodgieter': typeof WebsiteLatenMakenLoodgieterRoute
  '/website-laten-maken-makelaar': typeof WebsiteLatenMakenMakelaarRoute
  '/website-laten-maken-meppel': typeof WebsiteLatenMakenMeppelRoute
  '/website-laten-maken-nagelstudio': typeof WebsiteLatenMakenNagelstudioRoute
  '/website-laten-maken-pedicure': typeof WebsiteLatenMakenPedicureRoute
  '/website-laten-maken-restaurant': typeof WebsiteLatenMakenRestaurantRoute
  '/website-laten-maken-roden': typeof WebsiteLatenMakenRodenRoute
  '/website-laten-maken-schilder': typeof WebsiteLatenMakenSchilderRoute
  '/website-laten-maken-schoonheidssalon': typeof WebsiteLatenMakenSchoonheidssalonRoute
  '/website-laten-maken-sneek': typeof WebsiteLatenMakenSneekRoute
  '/website-laten-maken-stadskanaal': typeof WebsiteLatenMakenStadskanaalRoute
  '/website-laten-maken-veendam': typeof WebsiteLatenMakenVeendamRoute
  '/website-laten-maken-winschoten': typeof WebsiteLatenMakenWinschotenRoute
  '/website-laten-vernieuwen': typeof WebsiteLatenVernieuwenRoute
  '/werkwijze': typeof WerkwijzeRoute
  '/wordpress-of-maatwerk': typeof WordpressOfMaatwerkRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/server': typeof AuthenticatedServerRoute
  '/_authenticated/admin/accounts': typeof AuthenticatedAdminAccountsRouteWithChildren
  '/_authenticated/admin/changes': typeof AuthenticatedAdminChangesRouteWithChildren
  '/_authenticated/admin/instellingen': typeof AuthenticatedAdminInstellingenRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/projecten': typeof AuthenticatedAdminProjectenRouteWithChildren
  '/_authenticated/admin/rollen': typeof AuthenticatedAdminRollenRouteWithChildren
  '/api/public/site-error': typeof ApiPublicSiteErrorRoute
  '/api/public/site-ping': typeof ApiPublicSitePingRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/_authenticated/admin/accounts/$accountId': typeof AuthenticatedAdminAccountsAccountIdRoute
  '/_authenticated/admin/changes/$changeId': typeof AuthenticatedAdminChangesChangeIdRoute
  '/_authenticated/admin/projecten/$projectId': typeof AuthenticatedAdminProjectenProjectIdRoute
  '/_authenticated/admin/rollen/$roleId': typeof AuthenticatedAdminRollenRoleIdRoute
  '/_authenticated/portal/projecten/$projectId': typeof AuthenticatedPortalProjectenProjectIdRoute
  '/api/public/hooks/expire-accounts': typeof ApiPublicHooksExpireAccountsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/algemene-voorwaarden'
    | '/branches'
    | '/contact'
    | '/faq'
    | '/login'
    | '/meer-diensten'
    | '/onderhoud-hosting'
    | '/over-ons'
    | '/privacybeleid'
    | '/seo'
    | '/sitemap.xml'
    | '/tarieven'
    | '/track.js'
    | '/webdesign'
    | '/webshop-laten-maken'
    | '/website-laten-maken'
    | '/website-laten-maken-assen'
    | '/website-laten-maken-autobedrijf'
    | '/website-laten-maken-autorijschool'
    | '/website-laten-maken-bloemist'
    | '/website-laten-maken-boekhouder'
    | '/website-laten-maken-cateringbedrijf'
    | '/website-laten-maken-coevorden'
    | '/website-laten-maken-drachten'
    | '/website-laten-maken-emmen'
    | '/website-laten-maken-groningen'
    | '/website-laten-maken-heerenveen'
    | '/website-laten-maken-hoogeveen'
    | '/website-laten-maken-hoogezand'
    | '/website-laten-maken-hovenier'
    | '/website-laten-maken-kapsalon'
    | '/website-laten-maken-klusbedrijf'
    | '/website-laten-maken-leeuwarden'
    | '/website-laten-maken-loodgieter'
    | '/website-laten-maken-makelaar'
    | '/website-laten-maken-meppel'
    | '/website-laten-maken-nagelstudio'
    | '/website-laten-maken-pedicure'
    | '/website-laten-maken-restaurant'
    | '/website-laten-maken-roden'
    | '/website-laten-maken-schilder'
    | '/website-laten-maken-schoonheidssalon'
    | '/website-laten-maken-sneek'
    | '/website-laten-maken-stadskanaal'
    | '/website-laten-maken-veendam'
    | '/website-laten-maken-winschoten'
    | '/website-laten-vernieuwen'
    | '/werkwijze'
    | '/wordpress-of-maatwerk'
    | '/account'
    | '/admin'
    | '/portal'
    | '/server'
    | '/admin/accounts'
    | '/admin/changes'
    | '/admin/instellingen'
    | '/admin/leads'
    | '/admin/projecten'
    | '/admin/rollen'
    | '/api/public/site-error'
    | '/api/public/site-ping'
    | '/api/telegram/webhook'
    | '/admin/accounts/$accountId'
    | '/admin/changes/$changeId'
    | '/admin/projecten/$projectId'
    | '/admin/rollen/$roleId'
    | '/portal/projecten/$projectId'
    | '/api/public/hooks/expire-accounts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/algemene-voorwaarden'
    | '/branches'
    | '/contact'
    | '/faq'
    | '/login'
    | '/meer-diensten'
    | '/onderhoud-hosting'
    | '/over-ons'
    | '/privacybeleid'
    | '/seo'
    | '/sitemap.xml'
    | '/tarieven'
    | '/track.js'
    | '/webdesign'
    | '/webshop-laten-maken'
    | '/website-laten-maken'
    | '/website-laten-maken-assen'
    | '/website-laten-maken-autobedrijf'
    | '/website-laten-maken-autorijschool'
    | '/website-laten-maken-bloemist'
    | '/website-laten-maken-boekhouder'
    | '/website-laten-maken-cateringbedrijf'
    | '/website-laten-maken-coevorden'
    | '/website-laten-maken-drachten'
    | '/website-laten-maken-emmen'
    | '/website-laten-maken-groningen'
    | '/website-laten-maken-heerenveen'
    | '/website-laten-maken-hoogeveen'
    | '/website-laten-maken-hoogezand'
    | '/website-laten-maken-hovenier'
    | '/website-laten-maken-kapsalon'
    | '/website-laten-maken-klusbedrijf'
    | '/website-laten-maken-leeuwarden'
    | '/website-laten-maken-loodgieter'
    | '/website-laten-maken-makelaar'
    | '/website-laten-maken-meppel'
    | '/website-laten-maken-nagelstudio'
    | '/website-laten-maken-pedicure'
    | '/website-laten-maken-restaurant'
    | '/website-laten-maken-roden'
    | '/website-laten-maken-schilder'
    | '/website-laten-maken-schoonheidssalon'
    | '/website-laten-maken-sneek'
    | '/website-laten-maken-stadskanaal'
    | '/website-laten-maken-veendam'
    | '/website-laten-maken-winschoten'
    | '/website-laten-vernieuwen'
    | '/werkwijze'
    | '/wordpress-of-maatwerk'
    | '/account'
    | '/admin'
    | '/portal'
    | '/server'
    | '/admin/accounts'
    | '/admin/changes'
    | '/admin/instellingen'
    | '/admin/leads'
    | '/admin/projecten'
    | '/admin/rollen'
    | '/api/public/site-error'
    | '/api/public/site-ping'
    | '/api/telegram/webhook'
    | '/admin/accounts/$accountId'
    | '/admin/changes/$changeId'
    | '/admin/projecten/$projectId'
    | '/admin/rollen/$roleId'
    | '/portal/projecten/$projectId'
    | '/api/public/hooks/expire-accounts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/algemene-voorwaarden'
    | '/branches'
    | '/contact'
    | '/faq'
    | '/login'
    | '/meer-diensten'
    | '/onderhoud-hosting'
    | '/over-ons'
    | '/privacybeleid'
    | '/seo'
    | '/sitemap.xml'
    | '/tarieven'
    | '/track.js'
    | '/webdesign'
    | '/webshop-laten-maken'
    | '/website-laten-maken'
    | '/website-laten-maken-assen'
    | '/website-laten-maken-autobedrijf'
    | '/website-laten-maken-autorijschool'
    | '/website-laten-maken-bloemist'
    | '/website-laten-maken-boekhouder'
    | '/website-laten-maken-cateringbedrijf'
    | '/website-laten-maken-coevorden'
    | '/website-laten-maken-drachten'
    | '/website-laten-maken-emmen'
    | '/website-laten-maken-groningen'
    | '/website-laten-maken-heerenveen'
    | '/website-laten-maken-hoogeveen'
    | '/website-laten-maken-hoogezand'
    | '/website-laten-maken-hovenier'
    | '/website-laten-maken-kapsalon'
    | '/website-laten-maken-klusbedrijf'
    | '/website-laten-maken-leeuwarden'
    | '/website-laten-maken-loodgieter'
    | '/website-laten-maken-makelaar'
    | '/website-laten-maken-meppel'
    | '/website-laten-maken-nagelstudio'
    | '/website-laten-maken-pedicure'
    | '/website-laten-maken-restaurant'
    | '/website-laten-maken-roden'
    | '/website-laten-maken-schilder'
    | '/website-laten-maken-schoonheidssalon'
    | '/website-laten-maken-sneek'
    | '/website-laten-maken-stadskanaal'
    | '/website-laten-maken-veendam'
    | '/website-laten-maken-winschoten'
    | '/website-laten-vernieuwen'
    | '/werkwijze'
    | '/wordpress-of-maatwerk'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/_authenticated/server'
    | '/_authenticated/admin/accounts'
    | '/_authenticated/admin/changes'
    | '/_authenticated/admin/instellingen'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/projecten'
    | '/_authenticated/admin/rollen'
    | '/api/public/site-error'
    | '/api/public/site-ping'
    | '/api/telegram/webhook'
    | '/_authenticated/admin/accounts/$accountId'
    | '/_authenticated/admin/changes/$changeId'
    | '/_authenticated/admin/projecten/$projectId'
    | '/_authenticated/admin/rollen/$roleId'
    | '/_authenticated/portal/projecten/$projectId'
    | '/api/public/hooks/expire-accounts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AlgemeneVoorwaardenRoute: typeof AlgemeneVoorwaardenRoute
  BranchesRoute: typeof BranchesRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  MeerDienstenRoute: typeof MeerDienstenRoute
  OnderhoudHostingRoute: typeof OnderhoudHostingRoute
  OverOnsRoute: typeof OverOnsRoute
  PrivacybeleidRoute: typeof PrivacybeleidRoute
  SeoRoute: typeof SeoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TarievenRoute: typeof TarievenRoute
  TrackDotjsRoute: typeof TrackDotjsRoute
  WebdesignRoute: typeof WebdesignRoute
  WebshopLatenMakenRoute: typeof WebshopLatenMakenRoute
  WebsiteLatenMakenRoute: typeof WebsiteLatenMakenRoute
  WebsiteLatenMakenAssenRoute: typeof WebsiteLatenMakenAssenRoute
  WebsiteLatenMakenAutobedrijfRoute: typeof WebsiteLatenMakenAutobedrijfRoute
  WebsiteLatenMakenAutorijschoolRoute: typeof WebsiteLatenMakenAutorijschoolRoute
  WebsiteLatenMakenBloemistRoute: typeof WebsiteLatenMakenBloemistRoute
  WebsiteLatenMakenBoekhouderRoute: typeof WebsiteLatenMakenBoekhouderRoute
  WebsiteLatenMakenCateringbedrijfRoute: typeof WebsiteLatenMakenCateringbedrijfRoute
  WebsiteLatenMakenCoevordenRoute: typeof WebsiteLatenMakenCoevordenRoute
  WebsiteLatenMakenDrachtenRoute: typeof WebsiteLatenMakenDrachtenRoute
  WebsiteLatenMakenEmmenRoute: typeof WebsiteLatenMakenEmmenRoute
  WebsiteLatenMakenGroningenRoute: typeof WebsiteLatenMakenGroningenRoute
  WebsiteLatenMakenHeerenveenRoute: typeof WebsiteLatenMakenHeerenveenRoute
  WebsiteLatenMakenHoogeveenRoute: typeof WebsiteLatenMakenHoogeveenRoute
  WebsiteLatenMakenHoogezandRoute: typeof WebsiteLatenMakenHoogezandRoute
  WebsiteLatenMakenHovenierRoute: typeof WebsiteLatenMakenHovenierRoute
  WebsiteLatenMakenKapsalonRoute: typeof WebsiteLatenMakenKapsalonRoute
  WebsiteLatenMakenKlusbedrijfRoute: typeof WebsiteLatenMakenKlusbedrijfRoute
  WebsiteLatenMakenLeeuwardenRoute: typeof WebsiteLatenMakenLeeuwardenRoute
  WebsiteLatenMakenLoodgieterRoute: typeof WebsiteLatenMakenLoodgieterRoute
  WebsiteLatenMakenMakelaarRoute: typeof WebsiteLatenMakenMakelaarRoute
  WebsiteLatenMakenMeppelRoute: typeof WebsiteLatenMakenMeppelRoute
  WebsiteLatenMakenNagelstudioRoute: typeof WebsiteLatenMakenNagelstudioRoute
  WebsiteLatenMakenPedicureRoute: typeof WebsiteLatenMakenPedicureRoute
  WebsiteLatenMakenRestaurantRoute: typeof WebsiteLatenMakenRestaurantRoute
  WebsiteLatenMakenRodenRoute: typeof WebsiteLatenMakenRodenRoute
  WebsiteLatenMakenSchilderRoute: typeof WebsiteLatenMakenSchilderRoute
  WebsiteLatenMakenSchoonheidssalonRoute: typeof WebsiteLatenMakenSchoonheidssalonRoute
  WebsiteLatenMakenSneekRoute: typeof WebsiteLatenMakenSneekRoute
  WebsiteLatenMakenStadskanaalRoute: typeof WebsiteLatenMakenStadskanaalRoute
  WebsiteLatenMakenVeendamRoute: typeof WebsiteLatenMakenVeendamRoute
  WebsiteLatenMakenWinschotenRoute: typeof WebsiteLatenMakenWinschotenRoute
  WebsiteLatenVernieuwenRoute: typeof WebsiteLatenVernieuwenRoute
  WerkwijzeRoute: typeof WerkwijzeRoute
  WordpressOfMaatwerkRoute: typeof WordpressOfMaatwerkRoute
  ApiPublicSiteErrorRoute: typeof ApiPublicSiteErrorRoute
  ApiPublicSitePingRoute: typeof ApiPublicSitePingRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
  ApiPublicHooksExpireAccountsRoute: typeof ApiPublicHooksExpireAccountsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wordpress-of-maatwerk': {
      id: '/wordpress-of-maatwerk'
      path: '/wordpress-of-maatwerk'
      fullPath: '/wordpress-of-maatwerk'
      preLoaderRoute: typeof WordpressOfMaatwerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/werkwijze': {
      id: '/werkwijze'
      path: '/werkwijze'
      fullPath: '/werkwijze'
      preLoaderRoute: typeof WerkwijzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-vernieuwen': {
      id: '/website-laten-vernieuwen'
      path: '/website-laten-vernieuwen'
      fullPath: '/website-laten-vernieuwen'
      preLoaderRoute: typeof WebsiteLatenVernieuwenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-winschoten': {
      id: '/website-laten-maken-winschoten'
      path: '/website-laten-maken-winschoten'
      fullPath: '/website-laten-maken-winschoten'
      preLoaderRoute: typeof WebsiteLatenMakenWinschotenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-veendam': {
      id: '/website-laten-maken-veendam'
      path: '/website-laten-maken-veendam'
      fullPath: '/website-laten-maken-veendam'
      preLoaderRoute: typeof WebsiteLatenMakenVeendamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-stadskanaal': {
      id: '/website-laten-maken-stadskanaal'
      path: '/website-laten-maken-stadskanaal'
      fullPath: '/website-laten-maken-stadskanaal'
      preLoaderRoute: typeof WebsiteLatenMakenStadskanaalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-sneek': {
      id: '/website-laten-maken-sneek'
      path: '/website-laten-maken-sneek'
      fullPath: '/website-laten-maken-sneek'
      preLoaderRoute: typeof WebsiteLatenMakenSneekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-schoonheidssalon': {
      id: '/website-laten-maken-schoonheidssalon'
      path: '/website-laten-maken-schoonheidssalon'
      fullPath: '/website-laten-maken-schoonheidssalon'
      preLoaderRoute: typeof WebsiteLatenMakenSchoonheidssalonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-schilder': {
      id: '/website-laten-maken-schilder'
      path: '/website-laten-maken-schilder'
      fullPath: '/website-laten-maken-schilder'
      preLoaderRoute: typeof WebsiteLatenMakenSchilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-roden': {
      id: '/website-laten-maken-roden'
      path: '/website-laten-maken-roden'
      fullPath: '/website-laten-maken-roden'
      preLoaderRoute: typeof WebsiteLatenMakenRodenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-restaurant': {
      id: '/website-laten-maken-restaurant'
      path: '/website-laten-maken-restaurant'
      fullPath: '/website-laten-maken-restaurant'
      preLoaderRoute: typeof WebsiteLatenMakenRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-pedicure': {
      id: '/website-laten-maken-pedicure'
      path: '/website-laten-maken-pedicure'
      fullPath: '/website-laten-maken-pedicure'
      preLoaderRoute: typeof WebsiteLatenMakenPedicureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-nagelstudio': {
      id: '/website-laten-maken-nagelstudio'
      path: '/website-laten-maken-nagelstudio'
      fullPath: '/website-laten-maken-nagelstudio'
      preLoaderRoute: typeof WebsiteLatenMakenNagelstudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-meppel': {
      id: '/website-laten-maken-meppel'
      path: '/website-laten-maken-meppel'
      fullPath: '/website-laten-maken-meppel'
      preLoaderRoute: typeof WebsiteLatenMakenMeppelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-makelaar': {
      id: '/website-laten-maken-makelaar'
      path: '/website-laten-maken-makelaar'
      fullPath: '/website-laten-maken-makelaar'
      preLoaderRoute: typeof WebsiteLatenMakenMakelaarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-loodgieter': {
      id: '/website-laten-maken-loodgieter'
      path: '/website-laten-maken-loodgieter'
      fullPath: '/website-laten-maken-loodgieter'
      preLoaderRoute: typeof WebsiteLatenMakenLoodgieterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-leeuwarden': {
      id: '/website-laten-maken-leeuwarden'
      path: '/website-laten-maken-leeuwarden'
      fullPath: '/website-laten-maken-leeuwarden'
      preLoaderRoute: typeof WebsiteLatenMakenLeeuwardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-klusbedrijf': {
      id: '/website-laten-maken-klusbedrijf'
      path: '/website-laten-maken-klusbedrijf'
      fullPath: '/website-laten-maken-klusbedrijf'
      preLoaderRoute: typeof WebsiteLatenMakenKlusbedrijfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-kapsalon': {
      id: '/website-laten-maken-kapsalon'
      path: '/website-laten-maken-kapsalon'
      fullPath: '/website-laten-maken-kapsalon'
      preLoaderRoute: typeof WebsiteLatenMakenKapsalonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-hovenier': {
      id: '/website-laten-maken-hovenier'
      path: '/website-laten-maken-hovenier'
      fullPath: '/website-laten-maken-hovenier'
      preLoaderRoute: typeof WebsiteLatenMakenHovenierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-hoogezand': {
      id: '/website-laten-maken-hoogezand'
      path: '/website-laten-maken-hoogezand'
      fullPath: '/website-laten-maken-hoogezand'
      preLoaderRoute: typeof WebsiteLatenMakenHoogezandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-hoogeveen': {
      id: '/website-laten-maken-hoogeveen'
      path: '/website-laten-maken-hoogeveen'
      fullPath: '/website-laten-maken-hoogeveen'
      preLoaderRoute: typeof WebsiteLatenMakenHoogeveenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-heerenveen': {
      id: '/website-laten-maken-heerenveen'
      path: '/website-laten-maken-heerenveen'
      fullPath: '/website-laten-maken-heerenveen'
      preLoaderRoute: typeof WebsiteLatenMakenHeerenveenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-groningen': {
      id: '/website-laten-maken-groningen'
      path: '/website-laten-maken-groningen'
      fullPath: '/website-laten-maken-groningen'
      preLoaderRoute: typeof WebsiteLatenMakenGroningenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-emmen': {
      id: '/website-laten-maken-emmen'
      path: '/website-laten-maken-emmen'
      fullPath: '/website-laten-maken-emmen'
      preLoaderRoute: typeof WebsiteLatenMakenEmmenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-drachten': {
      id: '/website-laten-maken-drachten'
      path: '/website-laten-maken-drachten'
      fullPath: '/website-laten-maken-drachten'
      preLoaderRoute: typeof WebsiteLatenMakenDrachtenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-coevorden': {
      id: '/website-laten-maken-coevorden'
      path: '/website-laten-maken-coevorden'
      fullPath: '/website-laten-maken-coevorden'
      preLoaderRoute: typeof WebsiteLatenMakenCoevordenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-cateringbedrijf': {
      id: '/website-laten-maken-cateringbedrijf'
      path: '/website-laten-maken-cateringbedrijf'
      fullPath: '/website-laten-maken-cateringbedrijf'
      preLoaderRoute: typeof WebsiteLatenMakenCateringbedrijfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-boekhouder': {
      id: '/website-laten-maken-boekhouder'
      path: '/website-laten-maken-boekhouder'
      fullPath: '/website-laten-maken-boekhouder'
      preLoaderRoute: typeof WebsiteLatenMakenBoekhouderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-bloemist': {
      id: '/website-laten-maken-bloemist'
      path: '/website-laten-maken-bloemist'
      fullPath: '/website-laten-maken-bloemist'
      preLoaderRoute: typeof WebsiteLatenMakenBloemistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-autorijschool': {
      id: '/website-laten-maken-autorijschool'
      path: '/website-laten-maken-autorijschool'
      fullPath: '/website-laten-maken-autorijschool'
      preLoaderRoute: typeof WebsiteLatenMakenAutorijschoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-autobedrijf': {
      id: '/website-laten-maken-autobedrijf'
      path: '/website-laten-maken-autobedrijf'
      fullPath: '/website-laten-maken-autobedrijf'
      preLoaderRoute: typeof WebsiteLatenMakenAutobedrijfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-assen': {
      id: '/website-laten-maken-assen'
      path: '/website-laten-maken-assen'
      fullPath: '/website-laten-maken-assen'
      preLoaderRoute: typeof WebsiteLatenMakenAssenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken': {
      id: '/website-laten-maken'
      path: '/website-laten-maken'
      fullPath: '/website-laten-maken'
      preLoaderRoute: typeof WebsiteLatenMakenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webshop-laten-maken': {
      id: '/webshop-laten-maken'
      path: '/webshop-laten-maken'
      fullPath: '/webshop-laten-maken'
      preLoaderRoute: typeof WebshopLatenMakenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webdesign': {
      id: '/webdesign'
      path: '/webdesign'
      fullPath: '/webdesign'
      preLoaderRoute: typeof WebdesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track.js': {
      id: '/track.js'
      path: '/track.js'
      fullPath: '/track.js'
      preLoaderRoute: typeof TrackDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarieven': {
      id: '/tarieven'
      path: '/tarieven'
      fullPath: '/tarieven'
      preLoaderRoute: typeof TarievenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacybeleid': {
      id: '/privacybeleid'
      path: '/privacybeleid'
      fullPath: '/privacybeleid'
      preLoaderRoute: typeof PrivacybeleidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onderhoud-hosting': {
      id: '/onderhoud-hosting'
      path: '/onderhoud-hosting'
      fullPath: '/onderhoud-hosting'
      preLoaderRoute: typeof OnderhoudHostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meer-diensten': {
      id: '/meer-diensten'
      path: '/meer-diensten'
      fullPath: '/meer-diensten'
      preLoaderRoute: typeof MeerDienstenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algemene-voorwaarden': {
      id: '/algemene-voorwaarden'
      path: '/algemene-voorwaarden'
      fullPath: '/algemene-voorwaarden'
      preLoaderRoute: typeof AlgemeneVoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/server': {
      id: '/_authenticated/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof AuthenticatedServerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/telegram/webhook': {
      id: '/api/telegram/webhook'
      path: '/api/telegram/webhook'
      fullPath: '/api/telegram/webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site-ping': {
      id: '/api/public/site-ping'
      path: '/api/public/site-ping'
      fullPath: '/api/public/site-ping'
      preLoaderRoute: typeof ApiPublicSitePingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site-error': {
      id: '/api/public/site-error'
      path: '/api/public/site-error'
      fullPath: '/api/public/site-error'
      preLoaderRoute: typeof ApiPublicSiteErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/rollen': {
      id: '/_authenticated/admin/rollen'
      path: '/rollen'
      fullPath: '/admin/rollen'
      preLoaderRoute: typeof AuthenticatedAdminRollenRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projecten': {
      id: '/_authenticated/admin/projecten'
      path: '/projecten'
      fullPath: '/admin/projecten'
      preLoaderRoute: typeof AuthenticatedAdminProjectenRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/instellingen': {
      id: '/_authenticated/admin/instellingen'
      path: '/instellingen'
      fullPath: '/admin/instellingen'
      preLoaderRoute: typeof AuthenticatedAdminInstellingenRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/changes': {
      id: '/_authenticated/admin/changes'
      path: '/changes'
      fullPath: '/admin/changes'
      preLoaderRoute: typeof AuthenticatedAdminChangesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/accounts': {
      id: '/_authenticated/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AuthenticatedAdminAccountsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/expire-accounts': {
      id: '/api/public/hooks/expire-accounts'
      path: '/api/public/hooks/expire-accounts'
      fullPath: '/api/public/hooks/expire-accounts'
      preLoaderRoute: typeof ApiPublicHooksExpireAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/projecten/$projectId': {
      id: '/_authenticated/portal/projecten/$projectId'
      path: '/projecten/$projectId'
      fullPath: '/portal/projecten/$projectId'
      preLoaderRoute: typeof AuthenticatedPortalProjectenProjectIdRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/admin/rollen/$roleId': {
      id: '/_authenticated/admin/rollen/$roleId'
      path: '/$roleId'
      fullPath: '/admin/rollen/$roleId'
      preLoaderRoute: typeof AuthenticatedAdminRollenRoleIdRouteImport
      parentRoute: typeof AuthenticatedAdminRollenRoute
    }
    '/_authenticated/admin/projecten/$projectId': {
      id: '/_authenticated/admin/projecten/$projectId'
      path: '/$projectId'
      fullPath: '/admin/projecten/$projectId'
      preLoaderRoute: typeof AuthenticatedAdminProjectenProjectIdRouteImport
      parentRoute: typeof AuthenticatedAdminProjectenRoute
    }
    '/_authenticated/admin/changes/$changeId': {
      id: '/_authenticated/admin/changes/$changeId'
      path: '/$changeId'
      fullPath: '/admin/changes/$changeId'
      preLoaderRoute: typeof AuthenticatedAdminChangesChangeIdRouteImport
      parentRoute: typeof AuthenticatedAdminChangesRoute
    }
    '/_authenticated/admin/accounts/$accountId': {
      id: '/_authenticated/admin/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/admin/accounts/$accountId'
      preLoaderRoute: typeof AuthenticatedAdminAccountsAccountIdRouteImport
      parentRoute: typeof AuthenticatedAdminAccountsRoute
    }
  }
}

interface AuthenticatedAdminAccountsRouteChildren {
  AuthenticatedAdminAccountsAccountIdRoute: typeof AuthenticatedAdminAccountsAccountIdRoute
}

const AuthenticatedAdminAccountsRouteChildren: AuthenticatedAdminAccountsRouteChildren =
  {
    AuthenticatedAdminAccountsAccountIdRoute:
      AuthenticatedAdminAccountsAccountIdRoute,
  }

const AuthenticatedAdminAccountsRouteWithChildren =
  AuthenticatedAdminAccountsRoute._addFileChildren(
    AuthenticatedAdminAccountsRouteChildren,
  )

interface AuthenticatedAdminChangesRouteChildren {
  AuthenticatedAdminChangesChangeIdRoute: typeof AuthenticatedAdminChangesChangeIdRoute
}

const AuthenticatedAdminChangesRouteChildren: AuthenticatedAdminChangesRouteChildren =
  {
    AuthenticatedAdminChangesChangeIdRoute:
      AuthenticatedAdminChangesChangeIdRoute,
  }

const AuthenticatedAdminChangesRouteWithChildren =
  AuthenticatedAdminChangesRoute._addFileChildren(
    AuthenticatedAdminChangesRouteChildren,
  )

interface AuthenticatedAdminProjectenRouteChildren {
  AuthenticatedAdminProjectenProjectIdRoute: typeof AuthenticatedAdminProjectenProjectIdRoute
}

const AuthenticatedAdminProjectenRouteChildren: AuthenticatedAdminProjectenRouteChildren =
  {
    AuthenticatedAdminProjectenProjectIdRoute:
      AuthenticatedAdminProjectenProjectIdRoute,
  }

const AuthenticatedAdminProjectenRouteWithChildren =
  AuthenticatedAdminProjectenRoute._addFileChildren(
    AuthenticatedAdminProjectenRouteChildren,
  )

interface AuthenticatedAdminRollenRouteChildren {
  AuthenticatedAdminRollenRoleIdRoute: typeof AuthenticatedAdminRollenRoleIdRoute
}

const AuthenticatedAdminRollenRouteChildren: AuthenticatedAdminRollenRouteChildren =
  {
    AuthenticatedAdminRollenRoleIdRoute: AuthenticatedAdminRollenRoleIdRoute,
  }

const AuthenticatedAdminRollenRouteWithChildren =
  AuthenticatedAdminRollenRoute._addFileChildren(
    AuthenticatedAdminRollenRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAccountsRoute: typeof AuthenticatedAdminAccountsRouteWithChildren
  AuthenticatedAdminChangesRoute: typeof AuthenticatedAdminChangesRouteWithChildren
  AuthenticatedAdminInstellingenRoute: typeof AuthenticatedAdminInstellingenRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminProjectenRoute: typeof AuthenticatedAdminProjectenRouteWithChildren
  AuthenticatedAdminRollenRoute: typeof AuthenticatedAdminRollenRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAccountsRoute: AuthenticatedAdminAccountsRouteWithChildren,
  AuthenticatedAdminChangesRoute: AuthenticatedAdminChangesRouteWithChildren,
  AuthenticatedAdminInstellingenRoute: AuthenticatedAdminInstellingenRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminProjectenRoute:
    AuthenticatedAdminProjectenRouteWithChildren,
  AuthenticatedAdminRollenRoute: AuthenticatedAdminRollenRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalProjectenProjectIdRoute: typeof AuthenticatedPortalProjectenProjectIdRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalProjectenProjectIdRoute:
    AuthenticatedPortalProjectenProjectIdRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
  AuthenticatedServerRoute: typeof AuthenticatedServerRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
  AuthenticatedServerRoute: AuthenticatedServerRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AlgemeneVoorwaardenRoute: AlgemeneVoorwaardenRoute,
  BranchesRoute: BranchesRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  MeerDienstenRoute: MeerDienstenRoute,
  OnderhoudHostingRoute: OnderhoudHostingRoute,
  OverOnsRoute: OverOnsRoute,
  PrivacybeleidRoute: PrivacybeleidRoute,
  SeoRoute: SeoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TarievenRoute: TarievenRoute,
  TrackDotjsRoute: TrackDotjsRoute,
  WebdesignRoute: WebdesignRoute,
  WebshopLatenMakenRoute: WebshopLatenMakenRoute,
  WebsiteLatenMakenRoute: WebsiteLatenMakenRoute,
  WebsiteLatenMakenAssenRoute: WebsiteLatenMakenAssenRoute,
  WebsiteLatenMakenAutobedrijfRoute: WebsiteLatenMakenAutobedrijfRoute,
  WebsiteLatenMakenAutorijschoolRoute: WebsiteLatenMakenAutorijschoolRoute,
  WebsiteLatenMakenBloemistRoute: WebsiteLatenMakenBloemistRoute,
  WebsiteLatenMakenBoekhouderRoute: WebsiteLatenMakenBoekhouderRoute,
  WebsiteLatenMakenCateringbedrijfRoute: WebsiteLatenMakenCateringbedrijfRoute,
  WebsiteLatenMakenCoevordenRoute: WebsiteLatenMakenCoevordenRoute,
  WebsiteLatenMakenDrachtenRoute: WebsiteLatenMakenDrachtenRoute,
  WebsiteLatenMakenEmmenRoute: WebsiteLatenMakenEmmenRoute,
  WebsiteLatenMakenGroningenRoute: WebsiteLatenMakenGroningenRoute,
  WebsiteLatenMakenHeerenveenRoute: WebsiteLatenMakenHeerenveenRoute,
  WebsiteLatenMakenHoogeveenRoute: WebsiteLatenMakenHoogeveenRoute,
  WebsiteLatenMakenHoogezandRoute: WebsiteLatenMakenHoogezandRoute,
  WebsiteLatenMakenHovenierRoute: WebsiteLatenMakenHovenierRoute,
  WebsiteLatenMakenKapsalonRoute: WebsiteLatenMakenKapsalonRoute,
  WebsiteLatenMakenKlusbedrijfRoute: WebsiteLatenMakenKlusbedrijfRoute,
  WebsiteLatenMakenLeeuwardenRoute: WebsiteLatenMakenLeeuwardenRoute,
  WebsiteLatenMakenLoodgieterRoute: WebsiteLatenMakenLoodgieterRoute,
  WebsiteLatenMakenMakelaarRoute: WebsiteLatenMakenMakelaarRoute,
  WebsiteLatenMakenMeppelRoute: WebsiteLatenMakenMeppelRoute,
  WebsiteLatenMakenNagelstudioRoute: WebsiteLatenMakenNagelstudioRoute,
  WebsiteLatenMakenPedicureRoute: WebsiteLatenMakenPedicureRoute,
  WebsiteLatenMakenRestaurantRoute: WebsiteLatenMakenRestaurantRoute,
  WebsiteLatenMakenRodenRoute: WebsiteLatenMakenRodenRoute,
  WebsiteLatenMakenSchilderRoute: WebsiteLatenMakenSchilderRoute,
  WebsiteLatenMakenSchoonheidssalonRoute:
    WebsiteLatenMakenSchoonheidssalonRoute,
  WebsiteLatenMakenSneekRoute: WebsiteLatenMakenSneekRoute,
  WebsiteLatenMakenStadskanaalRoute: WebsiteLatenMakenStadskanaalRoute,
  WebsiteLatenMakenVeendamRoute: WebsiteLatenMakenVeendamRoute,
  WebsiteLatenMakenWinschotenRoute: WebsiteLatenMakenWinschotenRoute,
  WebsiteLatenVernieuwenRoute: WebsiteLatenVernieuwenRoute,
  WerkwijzeRoute: WerkwijzeRoute,
  WordpressOfMaatwerkRoute: WordpressOfMaatwerkRoute,
  ApiPublicSiteErrorRoute: ApiPublicSiteErrorRoute,
  ApiPublicSitePingRoute: ApiPublicSitePingRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
  ApiPublicHooksExpireAccountsRoute: ApiPublicHooksExpireAccountsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
