-- Batch 2: vult post_links met de interne links van alle 67 blogposts
-- (1-27 bestaand, 28-67 nieuw uit 20260917120000). Dit is de eerste echte
-- seeding van post_links sinds die tabel bestaat (20260917091000) — alle
-- links hieronder staan ook al inline in de markdown-content van de
-- betreffende posts. Vanaf nu wordt post_links automatisch herberekend bij
-- elke save via de admin-editor (zie syncPostLinks in blog.server.ts); deze
-- migratie zorgt dat het overzicht ook voor deze 67 posts meteen klopt,
-- zonder dat elke post eerst handmatig opnieuw opgeslagen hoeft te worden.
--
-- Alle links hier zijn blog-naar-blog (to_page_path blijft NULL); links naar
-- kernpagina's zoals /website-checker of /contact staan wel in de body maar
-- worden hier niet apart geregistreerd (zie de opmerking in de aangeleverde
-- contentlijst: "tenzij ze naar een andere blog wijzen").

INSERT INTO public.post_links (from_post_id, to_post_id, to_post_slug, to_page_path, anchor_text)
SELECT fp.id, tp.id, v.to_slug, NULL, v.anchor
FROM (VALUES
  ('wordpress-site-gehackt', 'backups-website-uitgelegd', 'goede back-ups'),
  ('wordpress-site-gehackt', 'ssl-certificaat-niet-veilig', 'een geldig SSL-certificaat'),
  ('core-web-vitals-website-snelheid', 'laadtijd-en-google-ranking', 'laadtijd en je Google-positie'),
  ('core-web-vitals-website-snelheid', 'cdn-uitgelegd', 'wat een CDN doet'),
  ('vps-hosting-kleine-bedrijven', 'domeinnaam-en-hosting-apart', 'domein en hosting apart houden'),
  ('vps-hosting-kleine-bedrijven', 'uptime-monitoring-website', 'uptime-monitoring'),
  ('gratis-website-checker-uitleg', 'checklist-nieuwe-website', 'of je toe bent aan een nieuwe website'),
  ('gratis-website-checker-uitleg', 'core-web-vitals-website-snelheid', 'de snelheid van je site'),
  ('google-business-profile-fouten', 'lokaal-beter-gevonden-google', 'lokaal beter gevonden worden'),
  ('google-business-profile-fouten', 'reviews-verzamelen-aanpak', 'reviews verzamelen'),
  ('mooi-versus-converteert', 'geen-aanvragen-via-website', 'waarom je geen aanvragen krijgt'),
  ('mooi-versus-converteert', 'teksten-voor-google-en-bezoekers', 'sterke website-teksten'),
  ('onderhoudskosten-na-livegang', 'kosten-onderhoud-hosting-per-maand', 'wat onderhoud per maand kost'),
  ('onderhoudskosten-na-livegang', 'backups-website-uitgelegd', 'back-ups'),
  ('webshop-vs-gewone-website', 'hoeveel-paginas-website-nodig', 'hoeveel pagina''s je nodig hebt'),
  ('webshop-vs-gewone-website', 'opbouw-website-prijs', 'wat een website kost'),
  ('verouderde-websites-groningen-drenthe', 'checklist-nieuwe-website', 'de checklist voor een nieuwe website'),
  ('verouderde-websites-groningen-drenthe', 'lokaal-beter-gevonden-google', 'lokale vindbaarheid'),
  ('checklist-nieuwe-website', 'gratis-website-checker-uitleg', 'de gratis website-checker'),
  ('checklist-nieuwe-website', 'redirects-nieuwe-website', 'redirects bij een nieuwe site'),
  ('ssl-certificaat-niet-veilig', 'is-mijn-website-avg-proof', 'de AVG-basis'),
  ('ssl-certificaat-niet-veilig', 'wordpress-site-gehackt', 'een gehackte site'),
  ('backups-website-uitgelegd', 'wordpress-site-gehackt', 'een hack'),
  ('backups-website-uitgelegd', 'onderhoudskosten-na-livegang', 'onderhoud na livegang'),
  ('contactformulier-faalt', 'geen-aanvragen-via-website', 'geen aanvragen via je site'),
  ('contactformulier-faalt', 'formulier-of-whatsapp-leads', 'formulier of WhatsApp'),
  ('mobile-first-design', 'responsive-vanaf-begin', 'responsive design vanaf het begin'),
  ('mobile-first-design', 'core-web-vitals-website-snelheid', 'snelheid op mobiel'),
  ('cdn-uitgelegd', 'core-web-vitals-website-snelheid', 'Core Web Vitals'),
  ('cdn-uitgelegd', 'laadtijd-en-google-ranking', 'laadtijd en ranking'),
  ('domeinnaam-en-hosting-apart', 'wat-is-dns-uitgelegd', 'hoe DNS werkt'),
  ('domeinnaam-en-hosting-apart', 'vps-hosting-kleine-bedrijven', 'self-hosten op een VPS'),
  ('laadtijd-en-google-ranking', 'core-web-vitals-website-snelheid', 'de Core Web Vitals'),
  ('laadtijd-en-google-ranking', 'goede-laadtijd-website', 'wat een goede laadtijd is'),
  ('cookiebanners-en-avg', 'is-mijn-website-avg-proof', 'of je site AVG-proof is'),
  ('cookiebanners-en-avg', 'google-analytics-vs-alternatieven', 'privacyvriendelijke statistieken'),
  ('404-pagina-en-foutafhandeling', 'redirects-nieuwe-website', 'redirects instellen'),
  ('404-pagina-en-foutafhandeling', 'opleveringschecklist-website', 'de oplevercheck'),
  ('gratis-website-bouwers-kosten', 'opbouw-website-prijs', 'wat een website echt kost'),
  ('gratis-website-bouwers-kosten', 'verschil-goedkope-dure-website', 'goedkoop versus duur'),
  ('ai-content-zonder-redactie-seo', 'teksten-voor-google-en-bezoekers', 'schrijven voor Google én bezoekers'),
  ('ai-content-zonder-redactie-seo', 'hoe-vaak-bloggen-voor-seo', 'hoe vaak je moet bloggen'),
  ('uptime-monitoring-website', 'hosting-uptime-uitgelegd', 'wat 99,9% uptime betekent'),
  ('uptime-monitoring-website', 'vps-hosting-kleine-bedrijven', 'hosting'),
  ('favicon-meta-titels-og-afbeeldingen', 'opleveringschecklist-website', 'de opleveringschecklist'),
  ('favicon-meta-titels-og-afbeeldingen', 'teksten-voor-google-en-bezoekers', 'goede meta-teksten'),
  ('wachtwoorden-delen-whatsapp', 'wordpress-site-gehackt', 'een hack voorkomen'),
  ('wachtwoorden-delen-whatsapp', 'ssl-certificaat-niet-veilig', 'beveiliging'),
  ('klantenportaal-tijdsbesparing', 'contactformulier-faalt', 'contact via je site'),
  ('klantenportaal-tijdsbesparing', 'opbouw-website-prijs', 'maatwerkfunctionaliteit'),
  ('webbureau-reageert-niet-website-terugkrijgen', 'juiste-webbureau-kiezen', 'een goed webbureau kiezen'),
  ('webbureau-reageert-niet-website-terugkrijgen', 'domeinnaam-en-hosting-apart', 'eigendom van domein en hosting'),
  ('structured-data-schema-markup', 'vindbaar-in-ai-zoekmachines', 'vindbaar in AI-zoekmachines'),
  ('structured-data-schema-markup', 'sitemap-belang', 'een goede sitemap'),
  ('eigen-emailadres-op-domein', 'domeinnaam-en-hosting-apart', 'domein en hosting'),
  ('eigen-emailadres-op-domein', 'wat-is-dns-uitgelegd', 'hoe DNS werkt'),
  ('wat-is-dns-uitgelegd', 'domeinnaam-en-hosting-apart', 'domein en hosting apart'),
  ('wat-is-dns-uitgelegd', 'redirects-nieuwe-website', 'een verhuizing zonder posities te verliezen'),
  ('hoeveel-paginas-website-nodig', 'waarom-bloggen-goed-voor-seo', 'een blog toevoegen'),
  ('hoeveel-paginas-website-nodig', 'webshop-vs-gewone-website', 'webshop of website'),
  ('stockfotos-website-nadelen', 'mooi-versus-converteert', 'mooi versus converteert'),
  ('stockfotos-website-nadelen', 'goede-over-ons-pagina', 'je over-ons-pagina'),
  ('google-analytics-vs-alternatieven', 'cookiebanners-en-avg', 'cookiebanners en AVG'),
  ('google-analytics-vs-alternatieven', 'is-mijn-website-avg-proof', 'AVG-proof zijn'),
  ('goede-over-ons-pagina', 'stockfotos-website-nadelen', 'echte foto''s in plaats van stock'),
  ('goede-over-ons-pagina', 'teksten-voor-google-en-bezoekers', 'sterke teksten'),
  ('waarom-bloggen-goed-voor-seo', 'hoe-vaak-bloggen-voor-seo', 'hoe vaak je moet bloggen'),
  ('waarom-bloggen-goed-voor-seo', 'teksten-voor-google-en-bezoekers', 'schrijven voor Google en bezoekers'),
  ('reviews-verzamelen-aanpak', 'google-business-profile-fouten', 'je Google Bedrijfsprofiel'),
  ('reviews-verzamelen-aanpak', 'lokaal-beter-gevonden-google', 'lokale vindbaarheid'),
  ('opbouw-website-prijs', 'website-laten-maken-kosten-mkb-2026', 'kosten voor het MKB in 2026'),
  ('opbouw-website-prijs', 'verschil-goedkope-dure-website', 'goedkoop versus duur'),
  ('responsive-vanaf-begin', 'mobile-first-design', 'mobile-first design'),
  ('responsive-vanaf-begin', 'goede-laadtijd-website', 'laadtijd op mobiel'),
  ('formulier-of-whatsapp-leads', 'contactformulier-faalt', 'een kapot contactformulier'),
  ('formulier-of-whatsapp-leads', 'snel-reageren-op-leads', 'snel reageren op leads'),
  ('hosting-uptime-uitgelegd', 'uptime-monitoring-website', 'uptime-monitoring'),
  ('hosting-uptime-uitgelegd', 'vps-hosting-kleine-bedrijven', 'betrouwbare hosting'),
  ('teksten-voor-ontwerp', 'mooi-versus-converteert', 'waarom mooi niet converteert'),
  ('teksten-voor-ontwerp', 'teksten-voor-google-en-bezoekers', 'schrijven voor Google en bezoekers'),
  ('redirects-nieuwe-website', '404-pagina-en-foutafhandeling', '404-fouten opvangen'),
  ('redirects-nieuwe-website', 'checklist-nieuwe-website', 'een nieuwe website'),
  ('tone-of-voice-uitgelegd', 'goede-over-ons-pagina', 'je over-ons-pagina'),
  ('tone-of-voice-uitgelegd', 'teksten-voor-google-en-bezoekers', 'je website-teksten'),
  ('lokale-seo-meerdere-plaatsen', 'lokaal-beter-gevonden-google', 'lokaal beter gevonden worden'),
  ('lokale-seo-meerdere-plaatsen', 'google-business-profile-fouten', 'je Google Bedrijfsprofiel'),
  ('sitemap-belang', 'structured-data-schema-markup', 'structured data'),
  ('sitemap-belang', 'website-niet-op-pagina-1-google', 'waarom je niet op pagina 1 staat'),
  ('ai-chatbot-website-nuttig', 'formulier-of-whatsapp-leads', 'formulier of WhatsApp'),
  ('ai-chatbot-website-nuttig', 'snel-reageren-op-leads', 'snel reageren op leads'),
  ('opleveringschecklist-website', 'redirects-nieuwe-website', 'redirects'),
  ('opleveringschecklist-website', 'favicon-meta-titels-og-afbeeldingen', 'favicon en meta-teksten'),
  ('snel-reageren-op-leads', 'contactformulier-faalt', 'een kapot contactformulier'),
  ('snel-reageren-op-leads', 'geen-aanvragen-via-website', 'geen aanvragen krijgen'),
  ('website-laten-maken-kosten-mkb-2026', 'opbouw-website-prijs', 'waar de prijs van afhangt'),
  ('website-laten-maken-kosten-mkb-2026', 'kosten-onderhoud-hosting-per-maand', 'maandelijkse onderhoudskosten'),
  ('hoger-in-google-zonder-specialist', 'google-business-profile-fouten', 'je Google Bedrijfsprofiel'),
  ('hoger-in-google-zonder-specialist', 'waarom-bloggen-goed-voor-seo', 'bloggen voor SEO'),
  ('hoe-lang-duurt-website-maken', 'opleveringschecklist-website', 'de oplevering'),
  ('hoe-lang-duurt-website-maken', 'opbouw-website-prijs', 'wat een website kost'),
  ('website-niet-op-pagina-1-google', 'hoger-in-google-zonder-specialist', 'zelf hoger komen in Google'),
  ('website-niet-op-pagina-1-google', 'hoe-lang-duurt-seo-resultaat', 'hoe lang SEO duurt'),
  ('hoe-vaak-bloggen-voor-seo', 'waarom-bloggen-goed-voor-seo', 'waarom bloggen helpt'),
  ('hoe-vaak-bloggen-voor-seo', 'teksten-voor-google-en-bezoekers', 'goede teksten schrijven'),
  ('verschil-seo-en-sea', 'google-ads-of-seo', 'Google Ads of SEO'),
  ('verschil-seo-en-sea', 'hoe-lang-duurt-seo-resultaat', 'hoe lang SEO duurt'),
  ('kosten-onderhoud-hosting-per-maand', 'onderhoudskosten-na-livegang', 'onderhoud na livegang'),
  ('kosten-onderhoud-hosting-per-maand', 'backups-website-uitgelegd', 'back-ups en beveiliging'),
  ('hoe-lang-duurt-seo-resultaat', 'website-niet-op-pagina-1-google', 'waarom je niet op pagina 1 staat'),
  ('hoe-lang-duurt-seo-resultaat', 'hoger-in-google-zonder-specialist', 'zelf aan SEO werken'),
  ('wordpress-of-maatwerk', 'opbouw-website-prijs', 'wat een website kost'),
  ('wordpress-of-maatwerk', 'verschil-goedkope-dure-website', 'goedkoop versus duur'),
  ('geen-aanvragen-via-website', 'contactformulier-faalt', 'een kapot contactformulier'),
  ('geen-aanvragen-via-website', 'mooi-versus-converteert', 'mooi versus converteert'),
  ('goede-laadtijd-website', 'core-web-vitals-website-snelheid', 'de Core Web Vitals'),
  ('goede-laadtijd-website', 'laadtijd-en-google-ranking', 'laadtijd en je ranking'),
  ('juiste-webbureau-kiezen', 'webbureau-reageert-niet-website-terugkrijgen', 'als je bureau niet reageert'),
  ('juiste-webbureau-kiezen', 'opbouw-website-prijs', 'wat een website kost'),
  ('domeinautoriteit-verhogen', 'wat-zijn-backlinks', 'wat backlinks zijn'),
  ('domeinautoriteit-verhogen', 'waarom-bloggen-goed-voor-seo', 'content die autoriteit opbouwt'),
  ('google-ads-of-seo', 'verschil-seo-en-sea', 'het verschil tussen SEO en SEA'),
  ('google-ads-of-seo', 'hoe-lang-duurt-seo-resultaat', 'hoe lang SEO duurt'),
  ('lokaal-beter-gevonden-google', 'google-business-profile-fouten', 'je Google Bedrijfsprofiel'),
  ('lokaal-beter-gevonden-google', 'lokale-seo-meerdere-plaatsen', 'vindbaar in meerdere plaatsen'),
  ('wat-zijn-backlinks', 'domeinautoriteit-verhogen', 'domeinautoriteit'),
  ('wat-zijn-backlinks', 'hoger-in-google-zonder-specialist', 'zelf aan SEO werken'),
  ('is-mijn-website-avg-proof', 'cookiebanners-en-avg', 'cookiebanners en AVG'),
  ('is-mijn-website-avg-proof', 'ssl-certificaat-niet-veilig', 'een geldig SSL-certificaat'),
  ('teksten-voor-google-en-bezoekers', 'teksten-voor-ontwerp', 'teksten vóór het ontwerp'),
  ('teksten-voor-google-en-bezoekers', 'ai-content-zonder-redactie-seo', 'AI-content zonder redactie'),
  ('verschil-goedkope-dure-website', 'opbouw-website-prijs', 'wat een website kost'),
  ('verschil-goedkope-dure-website', 'gratis-website-bouwers-kosten', 'gratis websitebouwers'),
  ('vindbaar-in-ai-zoekmachines', 'structured-data-schema-markup', 'structured data'),
  ('vindbaar-in-ai-zoekmachines', 'teksten-voor-google-en-bezoekers', 'helder schrijven')
) AS v(from_slug, to_slug, anchor)
JOIN public.blog_posts fp ON fp.slug = v.from_slug
JOIN public.blog_posts tp ON tp.slug = v.to_slug;
